- name: Polkachu 최신 Injective 스냅샷 다운로드 및 적용
  hosts: injective_nodes
  become: yes
  gather_facts: no

  tasks:

    - name: Set pruning and indexing options in config files
      block:
        - name: Configure app.toml for pruning
          lineinfile:
            path: "{{ injective_home }}/config/app.toml"
            regexp: '^pruning ='
            line: 'pruning = "custom"'

         # app.toml 기존 중복 설정 제거 후 재설정
        #- name: Ensure app.toml does not contain duplicate entries
         # shell: |
           # sed -i '/^pruning-keep-recent =/d' "{{ injective_home }}/config/app.toml"
           # sed -i '/^pruning-keep-every =/d' "{{ injective_home }}/config/app.toml"
           # sed -i '/^pruning-interval =/d' "{{ injective_home }}/config/app.toml"

        - name: Configure pruning strategy - keep recent
          lineinfile:
            path: "{{ injective_home }}/config/app.toml"
            regexp: '^pruning-keep-recent ='
            line: 'pruning-keep-recent = "100"'
            backrefs: yes
            create: yes

        - name: Configure pruning strategy - keep every
          lineinfile:
            path: "{{ injective_home }}/config/app.toml"
            regexp: '^pruning-keep-every ='
            line: 'pruning-keep-every = "0"'
            backrefs: yes
            create: yes

        - name: Configure pruning strategy - interval
          lineinfile:
            path: "{{ injective_home }}/config/app.toml"
            regexp: '^pruning-interval ='
            line: 'pruning-interval = "10"'
            backrefs: yes
            create: yes

        - name: Configure config.toml for indexer
          lineinfile:
            path: "{{ injective_home }}/config/config.toml"
            regexp: '^indexer ='
            line: 'indexer = "null"'
              
    - name: Polkachu Injective 스냅샷 페이지 가져오기
      uri:
        url: https://www.polkachu.com/tendermint_snapshots/injective
        return_content: yes
      register: polkachu_page

    - name: 최신 스냅샷 다운로드 URL 추출
      set_fact:
        latest_snapshot_url: "{{ polkachu_page.content | regex_search('href=\"(https://snapshots.polkachu.com/snapshots/injective/injective_[0-9]+\\.tar\\.lz4)\"', '\\1') | first }}"

    - name: 다운로드할 Polkachu 스냅샷 URL 확인
      debug:
        msg: "{{ latest_snapshot_url }}"

    - name: 스냅샷 파일명 추출
      set_fact:
        snapshot_filename: "{{ latest_snapshot_url | basename }}"

    - name: 최신 Injective 스냅샷 다운로드
      get_url:
        url: "{{ latest_snapshot_url }}"
        dest: "/home/ubuntu/{{ snapshot_filename }}"
        mode: '0644'
        force: yes

    - name: Injective 서비스 중지
      systemd:
        name: injectived
        state: stopped

    - name: 노드 상태 초기화
      command: injectived tendermint unsafe-reset-all --home /home/ubuntu/.injectived --keep-addr-book

    - name: priv_validator_state.json 백업
      copy:
        src: /home/ubuntu/.injectived/data/priv_validator_state.json
        dest: /home/ubuntu/.injectived/priv_validator_state.json
        remote_src: yes

    - name: 스냅샷 압축 해제 및 적용
      shell: |
        lz4 -c -d /home/ubuntu/{{ snapshot_filename }} | tar -x -C /home/ubuntu/.injectived
        chown -R ubuntu:ubuntu /home/ubuntu/.injectived

    - name: priv_validator_state.json 복원
      copy:
        src: /home/ubuntu/.injectived/priv_validator_state.json
        dest: /home/ubuntu/.injectived/data/priv_validator_state.json
        remote_src: yes

    - name: Injective 서비스 시작
      systemd:
        name: injectived
        state: started

