---
- name: Injective 최신 스냅샷 다운로드 및 적용
  hosts: injective_nodes
  become: yes
  gather_facts: yes

  tasks:
    - name: Fetch latest Injective snapshot URL from Imperator API
      shell: >
        curl -s https://api.imperator.co/services?network=mainnets |
        jq -r '.Injective.snapshots[0]["eu-west-1"][0].dl_url'
      register: latest_snapshot

    - name: Extract snapshot filename
      set_fact:
            snapshot_filename: "{{ latest_snapshot.stdout | basename }}"
  
    - name: Download latest Injective snapshot (with progress) 
      shell: >
        wget -c --progress=dot:mega -O /home/ubuntu/{{ snapshot_filename }} "{{ latest_snapshot.stdout }}"
      args:
       chdir: /home/ubuntu/
    
    - name: Stop Injective service if running
      shell: sudo systemctl stop injectived
      ignore_errors: yes
      async: 30  

    - name: Reset Injective node state
      shell: injectived tendermint unsafe-reset-all --home /home/ubuntu/.injectived --keep-addr-book     

    - name: priv_validator_state.json 백업
      command: cp /home/ubuntu/.injectived/data/priv_validator_state.json /home/ubuntu/.injectived/priv_validator_state.json
      ignore_errors: yes
  
    - name: Injective 스냅샷 압축 해제 및 적용
      shell: |
        zstd -d --stdout /home/ubuntu/{{ snapshot_filename }} | tar xf - -C /home/ubuntu/.injectived
        chown -R ubuntu:ubuntu /home/ubuntu/.injectived*
    
    - name: priv_validator_state.json 복원
      command: cp /home/ubuntu/.injectived/priv_validator_state.json /home/ubuntu/.injectived/data/priv_validator_state.json
      ignore_errors: yes

    - name: Restart Injective service 
      shell: systemctl restart injectived
      async: 30
      poll: 0

    - name: Injective 노드 상태 확인
      command: curl -s https://rpc-injective.imperator.co/status
      register: node_status

    - name: Injective 노드 동기화 상태 출력
      debug:
        msg: "{{ node_status.stdout | from_json | json_query('result.sync_info') }}"

