---
- name: Injective 최신 스냅샷 다운로드 및 적용
  hosts: injective_nodes
  become: yes
  gather_facts: yes

  tasks:
    - name: Fetch latest Injective snapshot URL from Imperator API
      shell: >
        curl -s https://api.imperator.co/services?network=mainnets | 
        jq -r '.Injective.snapshots[0]["eu-west-1"][0].dl_url'
      register: latest_snapshot

    - name: Extract snapshot filename
      set_fact:
            snapshot_filename: "{{ latest_snapshot.stdout | basename }}"

    - name: Download latest Injective snapshot (with progress)
      shell: >
        wget -c --progress=dot:mega -O /home/ubuntu/{{ snapshot_filename }} "{{ latest_snapshot.stdout }}"
      args:
       chdir: /home/ubuntu/    
    
          # - name: 다운로드 성공 여부 확인
          #debug:
          #msg: "스냅샷 다운로드 완료: /home/ubuntu/{{ snapshot_file }}"
          #when: download_result is succeeded

    - name: priv_validator_state.json 백업
      command: cp /home/ubuntu/.injectived/data/priv_validator_state.json /home/ubuntu/.injectived/priv_validator_state_backup.json
      ignore_errors: yes

    - name: Injective 스냅샷 압축 해제 및 적용
      command: >
        zstd -c -d --stdout /home/ubuntu/{{ snapshot_filename }} | tar xf - -C /home/ubuntu/.injectived

    - name: priv_validator_state.json 복원
      command: cp /home/ubuntu/.injectived/priv_validator_state_backup.json /home/ubuntu/.injectived/data/priv_validator_state.json
      ignore_errors: yes

    - name: Injective 노드 재시작
      systemd:
        name: injectived
        state: restarted
        enabled: yes

    - name: Injective 노드 상태 확인
      command: curl -s https://rpc-injective.imperator.co/status
      register: node_status

    - name: Injective 노드 동기화 상태 출력
      debug:
        msg: "{{ node_status.stdout | from_json | json_query('result.sync_info') }}"

