---
- name: Imperator latest snapshot install and applied to injective node
  hosts: injective_nodes
  become: yes
  gather_facts: yes

  tasks:
    - name: Fetch latest Injective snapshot URL from Imperator API
      shell: >
        curl -s https://api.imperator.co/services?network=mainnets | 
        jq -r '.Injective.snapshots[0]["eu-west-1"][0].dl_url'
      register: latest_snapshot

    - name: Extract snapshot filename
      set_fact:
            snapshot_filename: "{{ latest_snapshot.stdout | basename }}"

    - name: Download latest Injective snapshot (with progress)
      shell: >
        wget -c --progress=dot:mega -O /home/ubuntu/{{ snapshot_filename }} "{{ latest_snapshot.stdout }}"
      args:
       chdir: /home/ubuntu/    
    
          # - name: Check for success downloading
          #debug:
          #msg: "스냅샷 다운로드 완료: /home/ubuntu/{{ snapshot_file }}"
          #when: download_result is succeeded

    - name: priv_validator_state.json backup
      command: cp /home/ubuntu/.injectived/data/priv_validator_state.json /home/ubuntu/.injectived/priv_validator_state_backup.json
      ignore_errors: yes

    - name: Decompress Imperator snapshot flie
      command: >
        zstd -c -d --stdout /home/ubuntu/{{ snapshot_filename }} | tar xf - -C /home/ubuntu/.injectived

    - name: Restore priv_validator_state.json 
      command: cp /home/ubuntu/.injectived/priv_validator_state_backup.json /home/ubuntu/.injectived/data/priv_validator_state.json
      ignore_errors: yes

    - name: Restart injective service 
      systemd:
        name: injectived
        state: restarted
        enabled: yes

    - name: Check injective node status 
      command: curl -s https://rpc-injective.imperator.co/status
      register: node_status

    - name: Print out injective node sync status 
      debug:
        msg: "{{ node_status.stdout | from_json | json_query('result.sync_info') }}"

