name: Trigger Ansible Playbook for Injective

on:
  push:
    branches:
      - main  # main 브랜치에 Push될 때 실행

jobs:
  run-ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: |
          cd /home/ubuntu/injectived
          git pull
          ansible-playbook -i inventory.ini deploy_injective.yaml


