name: Trigger Ansible Playbook for Injective

on:
  push:
    branches:
      - main  # main 브랜치에 Push될 때 실행

jobs:
  run-ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: ansible-playbook -i localhost polcachu_snapshot.yaml


